# Generated by Django 5.2.7 on 2025-10-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_apellido_alter_usuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('DOC', 'Docente'), ('EST', 'Estudiante')], default='EST', max_length=10, verbose_name='Rol'),
        ),
    ]
