# Generated by Django 5.2.8 on 2025-11-23 19:21

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardGeneralProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Dashboard General',
                'verbose_name_plural': 'Dashboard General',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usuario.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
