# Generated by Django 5.2.8 on 2025-11-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del curso')),
                ('nivel', models.CharField(choices=[('BASICO', 'Básico'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], default='BASICO', max_length=10, verbose_name='Nivel')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio del curso')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin del curso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='SeleccionPacienteCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seleccion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Selección de paciente del curso',
                'verbose_name_plural': 'Selecciones de paciente del curso',
            },
        ),
    ]
