# Generated by Django 5.2.7 on 2025-11-13 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso_y_modulo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='docentes',
            field=models.ManyToManyField(blank=True, related_name='cursos_como_docente', to=settings.AUTH_USER_MODEL, verbose_name='Docentes'),
        ),
        migrations.AddField(
            model_name='curso',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='cursos_como_estudiante', to=settings.AUTH_USER_MODEL, verbose_name='Estudiantes'),
        ),
    ]
