# Generated by Django 5.2.9 on 2025-12-03 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contenido', '0002_initial'),
        ('curso_y_modulo', '0001_initial'),
        ('diagnostico_paciente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidoasignado',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'rol': 'EST'}, on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contenidoasignado',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_tema', to='Contenido.tema'),
        ),
        migrations.AddField(
            model_name='contenidoasignado',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_video', to='Contenido.video'),
        ),
        migrations.AddField(
            model_name='curso',
            name='docentes',
            field=models.ManyToManyField(blank=True, related_name='cursos_como_docente', to=settings.AUTH_USER_MODEL, verbose_name='Docentes'),
        ),
        migrations.AddField(
            model_name='curso',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='cursos_como_estudiante', to=settings.AUTH_USER_MODEL, verbose_name='Estudiantes'),
        ),
        migrations.AddField(
            model_name='contenidoasignado',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_contenido', to='curso_y_modulo.curso'),
        ),
        migrations.AddField(
            model_name='seleccionpacientecurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecciones_paciente', to='curso_y_modulo.curso'),
        ),
        migrations.AddField(
            model_name='seleccionpacientecurso',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selecciones_en_curso', to='diagnostico_paciente.paciente'),
        ),
        migrations.AddField(
            model_name='seleccionpacientecurso',
            name='usuario',
            field=models.ForeignKey(limit_choices_to={'rol': 'EST'}, on_delete=django.db.models.deletion.CASCADE, related_name='selecciones_paciente_curso', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='seleccionpacientecurso',
            unique_together={('usuario', 'curso')},
        ),
    ]
