# Generated by Django 5.2.8 on 2025-11-12 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contenido', '0004_remove_tema_modulo_tema_curso'),
        ('curso_y_modulo', '0002_initial'),
        ('diagnostico_paciente', '0005_remove_casoclinico_modulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='modulos',
        ),
        migrations.DeleteModel(
            name='ContenidoAdicional',
        ),
        migrations.DeleteModel(
            name='Modulo',
        ),
    ]
