# Generated by Django 5.2.7 on 2025-10-31 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso_y_modulo', '0002_docente_contenidoadicional_curso_modulo_curso'),
        ('usuario', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_docente', to='curso_y_modulo.docente'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_usuario', to='usuario.usuario'),
        ),
    ]
