# Generated by Django 5.2.7 on 2025-11-18 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso_y_modulo', '0002_initial'),
        ('diagnostico_paciente', '0004_diagnostico_parte_cuerpo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin del curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio del curso'),
        ),
        migrations.CreateModel(
            name='SeleccionPacienteCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seleccion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecciones_paciente', to='curso_y_modulo.curso')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selecciones_en_curso', to='diagnostico_paciente.paciente')),
                ('usuario', models.ForeignKey(limit_choices_to={'rol': 'EST'}, on_delete=django.db.models.deletion.CASCADE, related_name='selecciones_paciente_curso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Selección de paciente del curso',
                'verbose_name_plural': 'Selecciones de paciente del curso',
                'unique_together': {('usuario', 'curso')},
            },
        ),
    ]
