# Generated by Django 5.2.9 on 2025-12-03 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contenido', '0002_initial'),
        ('curso_y_modulo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, help_text='Diagnóstico preliminar y sugerencias de tratamiento.', null=True, verbose_name='Descripción del Diagnóstico')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'ordering': ('paciente',),
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('antecedentes', models.TextField(help_text='Antecedentes relevantes del paciente', verbose_name='Antecedentes')),
                ('historial_medico', models.TextField(help_text='Resumen del historial médico', verbose_name='Historial médico')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ('apellidos', 'nombres'),
            },
        ),
        migrations.CreateModel(
            name='ParteCuerpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Parte del cuerpo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Parte del cuerpo',
                'verbose_name_plural': 'Partes del cuerpo',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='CasoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título del caso')),
                ('descripcion', models.TextField(verbose_name='Descripción general')),
                ('motivo_consulta', models.TextField(verbose_name='Motivo de consulta')),
                ('antecedentes', models.TextField(verbose_name='Antecedentes del caso')),
                ('historial_clinico', models.TextField(verbose_name='Historial clínico detallado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos_clinicos', to='curso_y_modulo.curso', verbose_name='Curso asociado')),
            ],
            options={
                'verbose_name': 'Caso clínico',
                'verbose_name_plural': 'Casos clínicos',
                'ordering': ('-fecha_creacion', 'titulo'),
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la etapa')),
                ('pregunta', models.TextField(help_text='Pregunta principal de esta etapa', verbose_name='Pregunta')),
                ('contenido_adicional_url', models.URLField(blank=True, help_text='Opcional', max_length=500, verbose_name='Contenido adicional (URL)')),
                ('contenido_adicional_archivo', models.FileField(blank=True, null=True, upload_to='contenidos_adicionales/', verbose_name='Contenido adicional (archivo)')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='diagnostico_paciente.casoclinico', verbose_name='Caso clínico')),
                ('preguntas', models.ManyToManyField(blank=True, related_name='etapas', to='Contenido.pregunta', verbose_name='Preguntas disponibles para esta etapa')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas', to='Contenido.video', verbose_name='Video asociado')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ('caso', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='HistorialCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales_curso', to='curso_y_modulo.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Historial de curso',
                'verbose_name_plural': 'Historiales de curso',
            },
        ),
    ]
