# Generated by Django 5.2.8 on 2025-11-12 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso_y_modulo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('edad', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad')),
                ('antecedentes', models.TextField(blank=True, help_text='Antecedentes relevantes del paciente', verbose_name='Antecedentes')),
                ('historial_medico', models.TextField(blank=True, help_text='Resumen del historial médico', verbose_name='Historial médico')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ('apellidos', 'nombres'),
            },
        ),
        migrations.CreateModel(
            name='ParteCuerpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Parte del cuerpo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Parte del cuerpo',
                'verbose_name_plural': 'Partes del cuerpo',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de respuesta')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='¿Respondió correctamente?')),
            ],
            options={
                'verbose_name': 'Progreso',
                'verbose_name_plural': 'Progresos',
                'ordering': ('-fecha_respuesta',),
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido de la respuesta')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='¿Es la respuesta correcta?')),
                ('retroalimentacion', models.TextField(blank=True, help_text='Texto que se muestra al estudiante después de responder', verbose_name='Retroalimentación')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'ordering': ('etapa', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TipoRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Tipo de respuesta')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de respuesta',
                'verbose_name_plural': 'Tipos de respuesta',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='CasoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título del caso')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción general')),
                ('motivo_consulta', models.TextField(blank=True, verbose_name='Motivo de consulta')),
                ('antecedentes', models.TextField(blank=True, verbose_name='Antecedentes del caso')),
                ('historial_clinico', models.TextField(blank=True, verbose_name='Historial clínico detallado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_clinicos', to='curso_y_modulo.curso', verbose_name='Curso asociado')),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_clinicos', to='curso_y_modulo.modulo', verbose_name='Módulo asociado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_clinicos', to='diagnostico_paciente.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Caso clínico',
                'verbose_name_plural': 'Casos clínicos',
                'ordering': ('-fecha_creacion', 'titulo'),
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la etapa')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de la etapa dentro del caso clínico', verbose_name='Orden')),
                ('pregunta', models.TextField(help_text='Pregunta principal de esta etapa', verbose_name='Pregunta o enunciado')),
                ('url_video', models.URLField(blank=True, help_text='Video explicativo u orientador (opcional)', max_length=300, verbose_name='Video asociado')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='diagnostico_paciente.casoclinico', verbose_name='Caso clínico')),
                ('parte_cuerpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas', to='diagnostico_paciente.partecuerpo', verbose_name='Parte del cuerpo relacionada')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ('caso', 'orden'),
            },
        ),
    ]
