# Generated by Django 5.2.8 on 2025-11-12 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostico_paciente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progreso',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'rol': 'EST'}, on_delete=django.db.models.deletion.CASCADE, related_name='progresos_clinicos', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='progreso',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='diagnostico_paciente.etapa', verbose_name='Etapa'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='diagnostico_paciente.etapa', verbose_name='Etapa asociada'),
        ),
        migrations.AddField(
            model_name='progreso',
            name='respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progresos', to='diagnostico_paciente.respuesta', verbose_name='Respuesta seleccionada'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='diagnostico_paciente.tiporespuesta', verbose_name='Tipo de respuesta'),
        ),
        migrations.AlterUniqueTogether(
            name='etapa',
            unique_together={('caso', 'orden')},
        ),
        migrations.AlterUniqueTogether(
            name='progreso',
            unique_together={('estudiante', 'etapa')},
        ),
    ]
