# Generated by Django 5.2.8 on 2025-11-30 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostico_paciente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcurso',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'rol': 'EST'}, on_delete=django.db.models.deletion.CASCADE, related_name='historiales_curso', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_asociadas', to='diagnostico_paciente.paciente'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='diagnostico_paciente.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='casoclinico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_clinicos', to='diagnostico_paciente.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='parte_cuerpo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas', to='diagnostico_paciente.partecuerpo', verbose_name='Parte del cuerpo relacionada'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='parte_cuerpo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos_en_parte', to='diagnostico_paciente.partecuerpo', verbose_name='Parte del Cuerpo Afectada'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='diagnostico_paciente.etapa', verbose_name='Etapa asociada'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='diagnostico_paciente.tiporespuesta', verbose_name='Tipo de respuesta'),
        ),
        migrations.AlterUniqueTogether(
            name='historialcurso',
            unique_together={('curso', 'estudiante')},
        ),
        migrations.AlterUniqueTogether(
            name='etapa',
            unique_together={('caso', 'orden')},
        ),
    ]
