# Generated by Django 5.2.8 on 2025-11-12 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso_y_modulo', '0002_initial'),
        ('diagnostico_paciente', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progreso',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='casoclinico',
            name='antecedentes',
            field=models.TextField(verbose_name='Antecedentes del caso'),
        ),
        migrations.AlterField(
            model_name='casoclinico',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos_clinicos', to='curso_y_modulo.curso', verbose_name='Curso asociado'),
        ),
        migrations.AlterField(
            model_name='casoclinico',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción general'),
        ),
        migrations.AlterField(
            model_name='casoclinico',
            name='historial_clinico',
            field=models.TextField(verbose_name='Historial clínico detallado'),
        ),
        migrations.AlterField(
            model_name='casoclinico',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos_clinicos', to='curso_y_modulo.modulo', verbose_name='Módulo asociado'),
        ),
        migrations.AlterField(
            model_name='casoclinico',
            name='motivo_consulta',
            field=models.TextField(verbose_name='Motivo de consulta'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='antecedentes',
            field=models.TextField(help_text='Antecedentes relevantes del paciente', verbose_name='Antecedentes'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.PositiveIntegerField(verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='historial_medico',
            field=models.TextField(help_text='Resumen del historial médico', verbose_name='Historial médico'),
        ),
        migrations.AlterField(
            model_name='progreso',
            name='es_correcta',
            field=models.BooleanField(default=False, verbose_name='¿Respuesta correcta?'),
        ),
        migrations.AlterField(
            model_name='progreso',
            name='respuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='diagnostico_paciente.respuesta', verbose_name='Respuesta seleccionada'),
        ),
        migrations.CreateModel(
            name='HistorialCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales_curso', to='curso_y_modulo.curso', verbose_name='Curso')),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'EST'}, on_delete=django.db.models.deletion.CASCADE, related_name='historiales_curso', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Historial de curso',
                'verbose_name_plural': 'Historiales de curso',
                'unique_together': {('curso', 'estudiante')},
            },
        ),
        migrations.AddField(
            model_name='progreso',
            name='historial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='diagnostico_paciente.historialcurso', verbose_name='Historial de curso'),
        ),
        migrations.RemoveField(
            model_name='progreso',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='progreso',
            name='etapa',
        ),
    ]
