# Generated by Django 5.2.8 on 2025-11-12 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico_paciente', '0003_alter_progreso_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progreso',
        ),
    ]
