# Generated by Django 5.2.7 on 2025-11-14 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico_paciente', '0003_diagnostico'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='parte_cuerpo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos_en_parte', to='diagnostico_paciente.partecuerpo', verbose_name='Parte del Cuerpo Afectada'),
        ),
    ]
