# Generated by Django 5.2.8 on 2025-11-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico_paciente', '0004_delete_progreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casoclinico',
            name='modulo',
        ),
        migrations.AddField(
            model_name='etapa',
            name='contenido_adicional_archivo',
            field=models.FileField(blank=True, null=True, upload_to='contenidos_adicionales/', verbose_name='Contenido adicional (archivo)'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='contenido_adicional_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Contenido adicional (URL)'),
        ),
    ]
