# Generated by Django 5.2.7 on 2025-10-30 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('estado_completado', models.BooleanField(default=False, verbose_name='Estado completado')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('url', models.URLField(max_length=300, verbose_name='URL del video')),
                ('duracion', models.PositiveIntegerField(help_text='Duración del video en segundos', verbose_name='Duración (segundos)')),
                ('orden', models.PositiveIntegerField(help_text='Posición del video dentro del tema', verbose_name='Orden')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Contenido.tema', verbose_name='Tema asociado')),
            ],
            options={
                'ordering': ['tema', 'orden'],
                'constraints': [models.UniqueConstraint(fields=('tema', 'orden'), name='unique_orden_por_tema')],
            },
        ),
    ]
