# Generated by Django 5.2.7 on 2025-10-30 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido de la pregunta')),
                ('orden', models.PositiveIntegerField(help_text='Posición de la pregunta dentro del video', verbose_name='Orden')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='Contenido.video', verbose_name='Video asociado')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['video', 'orden'],
                'constraints': [models.UniqueConstraint(fields=('video', 'orden'), name='unique_orden_por_video_en_pregunta')],
            },
        ),
    ]
