# Generated by Django 5.2.9 on 2025-12-03 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contenido', '0001_initial'),
        ('curso_y_modulo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temas', to='curso_y_modulo.curso', verbose_name='Curso asociado'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='topico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas', to='Contenido.topico', verbose_name='Tópico'),
        ),
        migrations.AddField(
            model_name='video',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contenido.tema'),
        ),
    ]
