# Generated by Django 5.2.7 on 2025-11-13 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contenido', '0001_initial'),
        ('diagnostico_paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaclinica',
            name='caso_clinico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_contenido', to='diagnostico_paciente.casoclinico', verbose_name='Caso clínico asociado'),
        ),
    ]
