# Generated by Django 5.2.7 on 2025-10-30 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenido', '0002_pregunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido de la respuesta')),
                ('retroalimentacion', models.TextField(blank=True, help_text='Explicación o feedback mostrado al estudiante después de responder', null=True, verbose_name='Retroalimentación')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='¿Es la respuesta correcta?')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='Contenido.pregunta', verbose_name='Pregunta asociada')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
    ]
