# Generated by Django 5.2.8 on 2025-11-12 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contenido', '0002_initial'),
        ('curso_y_modulo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'rol': 'EST'}, on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante asociado'),
        ),
        migrations.AddField(
            model_name='historial',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='Contenido.fichaclinica', verbose_name='Ficha clínica asociada'),
        ),
        migrations.AddField(
            model_name='buscador_de_respuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='Contenido.pregunta', verbose_name='Pregunta asociada'),
        ),
        migrations.AddField(
            model_name='tema',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas', to='curso_y_modulo.modulo', verbose_name='Módulo asociado'),
        ),
        migrations.AddField(
            model_name='historial',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='Contenido.tema', verbose_name='Tema asociado'),
        ),
        migrations.AddField(
            model_name='video',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Contenido.tema', verbose_name='Tema asociado'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='Contenido.video', verbose_name='Video asociado'),
        ),
        migrations.AddConstraint(
            model_name='historial',
            constraint=models.UniqueConstraint(fields=('tema', 'estudiante', 'ficha'), name='unique_tema_estudiante_ficha'),
        ),
        migrations.AlterUniqueTogether(
            name='pregunta',
            unique_together={('video', 'orden')},
        ),
    ]
