# Generated by Django 5.2.8 on 2025-11-12 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenido', '0003_initial'),
        ('curso_y_modulo', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='modulo',
        ),
        migrations.AddField(
            model_name='tema',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temas', to='curso_y_modulo.curso', verbose_name='Curso asociado'),
        ),
    ]
