# Generated by Django 5.2.7 on 2025-10-30 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenido', '0003_respuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='FichaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de la ficha clínica')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='Contenido.estudiante', verbose_name='Estudiante asociado')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='Contenido.fichaclinica', verbose_name='Ficha clínica asociada')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='Contenido.tema', verbose_name='Tema asociado')),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
                'ordering': ['-fecha_registro'],
                'constraints': [models.UniqueConstraint(fields=('tema', 'estudiante', 'ficha'), name='unique_tema_estudiante_ficha')],
            },
        ),
    ]
