# Generated by Django 5.2.7 on 2025-11-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenido', '0004_alter_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(max_length=300, verbose_name='URL del video'),
        ),
    ]
