# Generated by Django 5.2.7 on 2025-10-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre docente')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido docente')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('password', models.CharField(max_length=128, verbose_name='contraseña')),
            ],
        ),
    ]
